version: '3.8'

services:
  bundeskanzler-ki:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api_memory:/app/api_memory
      - ./corpus.json:/app/corpus.json
      - ./source_credibility.json:/app/source_credibility.json
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=""  # Deaktiviere GPU
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis für Caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    profiles:
      - with-redis

volumes:
  redis_data:

networks:
  default:
    name: bundeskanzler-network