# Modell-Konfiguration für die Bundeskanzler-KI

# Basis-Modell Konfiguration
model:
  vocab_size: 30000
  embedding_dim: 512
  hidden_dim: 768
  num_layers: 6
  num_heads: 8
  dropout: 0.1

# Memory-Netzwerk Konfiguration
memory:
  memory_size: 1000
  key_dim: 512
  num_heads: 8
  temporal_decay: 0.95
  update_threshold: 0.1

# Kontext-Prozessor Konfiguration
context:
  max_window_size: 50
  min_importance: 0.3
  source_weights:
    pressemitteilung: 1.2
    rede: 1.5
    interview: 1.3
    social_media: 0.8
  topic_weights:
    wirtschaft: 1.4
    außenpolitik: 1.3
    innenpolitik: 1.2
    klimaschutz: 1.3
    digitalisierung: 1.2

# Kategorie-Muster
categories:
  Wirtschaft:
    keywords:
      - wirtschaft
      - finanzen
      - haushalt
      - konjunktur
      - inflation
    phrases:
      - wirtschaftliche entwicklung
      - finanzielle situation
      - wirtschaftswachstum
      - haushaltsplanung
    context:
      - konjunktur
      - wachstum
      - märkte
      - investitionen

  Außenpolitik:
    keywords:
      - außenpolitik
      - international
      - diplomatie
      - beziehungen
      - zusammenarbeit
    phrases:
      - internationale beziehungen
      - außenpolitische lage
      - diplomatische gespräche
      - bilaterale zusammenarbeit
    context:
      - global
      - bilateral
      - multilateral
      - international

  Innenpolitik:
    keywords:
      - innenpolitik
      - reform
      - gesetz
      - bürger
      - gesellschaft
    phrases:
      - innere sicherheit
      - gesellschaftlicher zusammenhalt
      - politische reform
      - soziale gerechtigkeit
    context:
      - national
      - reform
      - gesellschaft
      - politik

  Klimaschutz:
    keywords:
      - klima
      - umwelt
      - nachhaltigkeit
      - energie
      - emission
    phrases:
      - klimaschutzmaßnahmen
      - energiewende
      - nachhaltiges wirtschaften
      - klimaziele
    context:
      - umwelt
      - energie
      - klimawandel
      - nachhaltigkeit

  Digitalisierung:
    keywords:
      - digital
      - technologie
      - innovation
      - internet
      - ki
    phrases:
      - digitale transformation
      - technologischer wandel
      - digitale infrastruktur
      - künstliche intelligenz
    context:
      - innovation
      - digital
      - technologie
      - zukunft

# Training Konfiguration
training:
  batch_size: 32
  learning_rate: 0.0001
  epochs: 200
  warmup_steps: 1000
  max_seq_length: 512
  validation_split: 0.2